"""make_project_id_nullable

Revision ID: 4f8298950e52
Revises: a3b4c5d6e7f8
Create Date: 2026-06-05 16:54:21.567004+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4f8298950e52'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_is_published'), table_name='certificates')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_index(op.f('ix_educations_is_published'), table_name='educations')
    op.drop_index(op.f('ix_educations_sort_order'), table_name='educations')
    op.drop_index(op.f('ix_experiences_is_published'), table_name='experiences')
    op.alter_column('project_github_metadata', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_skills_is_published'), table_name='skills')
    op.drop_index(op.f('ix_testimonials_is_published'), table_name='testimonials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_testimonials_is_published'), 'testimonials', ['is_published'], unique=False)
    op.create_index(op.f('ix_skills_is_published'), 'skills', ['is_published'], unique=False)
    op.alter_column('project_github_metadata', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_experiences_is_published'), 'experiences', ['is_published'], unique=False)
    op.create_index(op.f('ix_educations_sort_order'), 'educations', ['sort_order'], unique=False)
    op.create_index(op.f('ix_educations_is_published'), 'educations', ['is_published'], unique=False)
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_certificates_is_published'), 'certificates', ['is_published'], unique=False)
    # ### end Alembic commands ###
