"""add indexes and constraints

Revision ID: f1f9385888f2
Revises: cac54d5918f9
Create Date: 2026-06-10 16:45:54.678296+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f1f9385888f2'
down_revision: Union[str, None] = 'cac54d5918f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_unique_constraint('uq_project_skill', 'project_skills', ['project_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_skill', 'project_skills', type_='unique')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    # ### end Alembic commands ###
