"""Add is_deleted column for soft deletes

Revision ID: 9a6107482869
Revises: c3c9588624b1
Create Date: 2026-06-04 10:36:26.203193+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9a6107482869'
down_revision: Union[str, None] = 'c3c9588624b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_certificates_is_deleted'), 'certificates', ['is_deleted'], unique=False)
    op.add_column('educations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_educations_is_deleted'), 'educations', ['is_deleted'], unique=False)
    op.add_column('experiences', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_experiences_is_deleted'), 'experiences', ['is_deleted'], unique=False)
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.add_column('skills', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.add_column('testimonials', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_testimonials_is_deleted'), 'testimonials', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonials_is_deleted'), table_name='testimonials')
    op.drop_column('testimonials', 'is_deleted')
    op.drop_index(op.f('ix_skills_is_deleted'), table_name='skills')
    op.drop_column('skills', 'is_deleted')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_column('projects', 'is_deleted')
    op.drop_index(op.f('ix_experiences_is_deleted'), table_name='experiences')
    op.drop_column('experiences', 'is_deleted')
    op.drop_index(op.f('ix_educations_is_deleted'), table_name='educations')
    op.drop_column('educations', 'is_deleted')
    op.drop_index(op.f('ix_certificates_is_deleted'), table_name='certificates')
    op.drop_column('certificates', 'is_deleted')
    # ### end Alembic commands ###
