"""add is_active to project_github_metadata

Revision ID: cac54d5918f9
Revises: 4f8298950e52
Create Date: 2026-06-05 18:12:38.534176+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cac54d5918f9'
down_revision: Union[str, None] = '4f8298950e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_github_metadata', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_project_github_metadata_is_active'), 'project_github_metadata', ['is_active'], unique=False)
    op.drop_constraint(op.f('project_github_metadata_project_id_fkey'), 'project_github_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'project_github_metadata', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_github_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('project_github_metadata_project_id_fkey'), 'project_github_metadata', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_project_github_metadata_is_active'), table_name='project_github_metadata')
    op.drop_column('project_github_metadata', 'is_active')
    # ### end Alembic commands ###
